name: Maven Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 17, 21]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK {{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: '{{ matrix.jdk }}'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
